pub mod backend;
pub mod backup_catalog;
pub mod config;
pub mod console;
pub mod gptadmin;
pub mod index;
pub mod jobs;
pub mod mcp;
#[cfg(feature = "ocr")]
pub mod ocr;
#[cfg(not(feature = "ocr"))]
#[path = "ocr_disabled.rs"]
pub mod ocr;
pub mod server;
pub mod stt;
pub mod topology;
pub mod topology_cache;
pub mod userio;
