(() => {
  "use strict";

  const api = Object.freeze({ catalog: "/api/catalog", browse: "/api/browse", search: "/api/search", searchStatus: "/api/search/status", preview: "/api/preview", backup: "/api/backup/availability" });
  const $ = (id) => document.getElementById(id);
  const dom = {
    connection: $("connection"), form: $("search-form"), query: $("query"), refresh: $("refresh-catalog"),
    button: $("search-button"), state: $("search-state"), hosts: $("host-sidebar"), locations: $("locations-sidebar"), results: $("results"),
    count: $("results-count"), preview: $("preview"), failures: $("host-failures"), backupBadge: $("backup-badge"), backup: $("backup-body"),
  };
  const state = { catalog: null, selected: null, selectedHost: "", selectedRoot: null, browseTarget: null, results: [], mode: "browse" };

  function text(value) { return value == null ? "" : String(value); }
  function pick(object, keys, fallback = undefined) { for (const key of keys) if (object && object[key] !== undefined && object[key] !== null) return object[key]; return fallback; }
  function dataOf(payload) { return payload && typeof payload.data === "object" && !Array.isArray(payload.data) ? payload.data : (payload || {}); }
  function errorMessage(error) { return error instanceof Error ? error.message : text(error) || "The local API is unavailable."; }
  function clear(node) { node.replaceChildren(); return node; }
  function element(name, className, value) { const node = document.createElement(name); if (className) node.className = className; if (value !== undefined) node.textContent = text(value); return node; }
  function formatCount(count) { return `${count} ${count === 1 ? "match" : "matches"}`; }
  function setConnection(kind, message) { dom.connection.className = `connection ${kind || ""}`; dom.connection.lastElementChild.textContent = message; }
  function setSearchState(kind, message) { dom.state.className = `search-state ${kind}`; dom.state.lastElementChild.textContent = message; }
  async function request(url, options = {}) {
    const response = await fetch(url, { headers: { Accept: "application/json", ...(options.body ? { "Content-Type": "application/json" } : {}) }, ...options });
    const raw = await response.text(); let body = {};
    try { body = raw ? JSON.parse(raw) : {}; } catch { throw new Error("The local API returned an invalid response."); }
    if (!response.ok) throw new Error(pick(body, ["error", "message"], `Request failed (${response.status}).`));
    return body;
  }
  function catalogEntries(payload) {
    const source = dataOf(payload); const rawHosts = pick(source, ["hosts", "nodes", "available_hosts"], []);
    const hosts = (Array.isArray(rawHosts) ? rawHosts : []).map((entry) => ({ id: text(typeof entry === "string" ? entry : pick(entry, ["id", "host_id", "host"])), label: text(typeof entry === "string" ? entry : pick(entry, ["label", "name", "host_id", "id"])), health: text(typeof entry === "string" ? "unknown" : pick(entry, ["health"], "unknown")), lastError: text(typeof entry === "string" ? "" : pick(entry, ["last_error"], "")), roots: Array.isArray(entry?.roots) ? entry.roots.map((root) => ({ host: text(typeof root === "string" ? pick(entry, ["id", "host_id", "host"]) : pick(root, ["host", "host_id"], pick(entry, ["id", "host_id", "host"]))), path: text(typeof root === "string" ? root : pick(root, ["path", "root", "id"])), name: text(typeof root === "string" ? root : pick(root, ["name", "label", "path", "root", "id"])) })).filter((root) => root.host && root.path) : [] })).filter((entry) => entry.id);
    const rootValues = pick(source, ["roots", "available_roots"], []);
    const roots = hosts.flatMap((host) => host.roots);
    if (!roots.length) { const host = hosts.length === 1 ? hosts[0].id : ""; roots.push(...(Array.isArray(rootValues) ? rootValues : []).map((entry) => ({ host: text(typeof entry === "string" ? host : pick(entry, ["host", "host_id"], host)), path: text(typeof entry === "string" ? entry : pick(entry, ["id", "path", "root"])), name: text(typeof entry === "string" ? entry : pick(entry, ["name", "label", "path", "root", "id"])) })).filter((root) => root.path)); }
    return { hosts, roots: roots.filter((root, index, items) => items.findIndex((candidate) => candidate.host === root.host && candidate.path === root.path) === index) };
  }
  function visibleRoots() {
    const host = state.catalog?.hosts.find((item) => item.id === state.selectedHost);
    return host?.roots?.length ? host.roots : (state.catalog?.roots || []);
  }
  function resetPreview() {
    const preview = clear(dom.preview); preview.className = "preview-empty";
    preview.append(element("span", "empty-icon", "▧"), element("p", "No file selected."), element("small", "Choose a root or directory to browse metadata, or a search result to inspect its bounded preview."));
  }
  function renderHosts() {
    const hosts = clear(dom.hosts);
    const all = element("button", `host-item ${state.selectedHost ? "" : "selected"}`); all.type = "button"; all.append(element("span", "host-item-icon", "◉"), element("span", "", "All available hosts")); all.addEventListener("click", () => selectHost("")); hosts.append(all);
    (state.catalog?.hosts || []).forEach((host) => {
      const button = element("button", `host-item ${host.id === state.selectedHost ? "selected" : ""}`); button.type = "button";
      button.append(element("span", "host-item-icon", "◆"), element("span", "", host.label || host.id), element("small", `host-health ${host.health || "unknown"}`, host.health || "unknown"), element("small", "", host.lastError || (host.roots.length ? `${host.roots.length} root${host.roots.length === 1 ? "" : "s"}` : "catalog host")));
      button.addEventListener("click", () => selectHost(host.id)); hosts.append(button);
    });
  }
  function selectHost(hostId) { state.selectedHost = hostId; state.selectedRoot = null; state.browseTarget = null; state.selected = null; state.mode = "browse"; renderHosts(); renderLocations(); renderBrowsePlaceholder(); resetPreview(); }
  function selectRoot(root) { state.selectedRoot = root; state.browseTarget = root; state.selected = null; state.mode = "browse"; renderLocations(); resetPreview(); browseDirectory(root); }
  function selectLocation(event) { const button = event.target?.closest?.(".location-item"); if (!button || !dom.locations.contains(button)) return; const root = visibleRoots().find((candidate) => candidate.host === button.dataset.host && candidate.path === button.dataset.root); if (root) selectRoot(root); }
  function renderLocations() {
    const locations = clear(dom.locations); const roots = visibleRoots();
    if (!roots.length) { locations.append(element("p", "sidebar-empty", "No configured Locations are available for this Device.")); return; }
    roots.forEach((root) => {
      const button = element("button", `location-item ${root.path === state.selectedRoot?.path && root.host === state.selectedRoot?.host ? "selected" : ""}`); button.type = "button"; button.dataset.root = root.path; button.dataset.host = root.host;
      button.append(element("span", "location-icon", "▱"), element("span", "location-name", root.name || root.path), element("small", "", root.host || "configured drive")); locations.append(button);
    });
  }
  function renderBrowsePlaceholder() { clear(dom.results); dom.count.textContent = "Choose a Location"; const empty = element("div", "empty-results"); empty.append(element("span", "empty-icon", "▱"), element("p", "Select a Location to browse its immediate entries."), element("small", "Devices and Locations stay available in the sidebar while you browse.")); dom.results.append(empty); }
  function renderCatalog(payload) { state.catalog = catalogEntries(payload); if (state.selectedHost && !state.catalog.hosts.some((host) => host.id === state.selectedHost)) state.selectedHost = ""; if (state.selectedRoot && !state.catalog.roots.some((root) => root.host === state.selectedRoot.host && root.path === state.selectedRoot.path)) state.selectedRoot = null; renderHosts(); renderLocations(); if (!state.selectedRoot) renderBrowsePlaceholder(); setConnection("ready", state.catalog.hosts.length ? `${state.catalog.hosts.length} host${state.catalog.hosts.length === 1 ? "" : "s"} available` : "Catalog is ready"); }
  async function loadCatalog() { setConnection("", "Loading catalog…"); try { renderCatalog(await request(api.catalog)); } catch (error) { clear(dom.hosts).append(element("p", "sidebar-empty", "Catalog unavailable")); clear(dom.locations).append(element("p", "sidebar-empty", "Catalog unavailable")); clear(dom.results).append(element("div", "empty-results", `Catalog unavailable: ${errorMessage(error)}`)); setConnection("error", "Catalog unavailable"); setSearchState("error", `Catalog unavailable: ${errorMessage(error)}`); } }
  function normalizeEntries(payload, host) { const source = dataOf(payload); return (Array.isArray(source.entries) ? source.entries : []).map((entry, index) => ({ host: text(pick(entry, ["host_id", "host"], host)), name: text(pick(entry, ["name"], "Unnamed entry")), path: text(pick(entry, ["path"], "")), kind: text(pick(entry, ["kind"], "other")), size: pick(entry, ["size"]), modified: pick(entry, ["modified_ms"]), key: `${host}:${pick(entry, ["path"], index)}` })).filter((entry) => entry.path); }
  function browseEntryDetails(entry) { const content = clear(dom.preview); content.className = "preview-content"; const title = element("div", "preview-title"); title.append(element("code", "", entry.path), element("span", "", entry.kind)); const details = [entry.kind, entry.size == null ? "size unavailable" : `${entry.size} bytes`, entry.modified == null ? "modified time unavailable" : `modified ${new Date(Number(entry.modified)).toLocaleString()}`]; content.append(title, element("pre", "", details.join("\n")), element("small", "", entry.kind === "directory" ? "Listing immediate entries…" : "Browse selection is metadata-only. Search for bounded file content.")); }
  function renderBrowseEntries(entries) { clear(dom.results); dom.count.textContent = entries.length ? `${entries.length} ${entries.length === 1 ? "entry" : "entries"}` : "No immediate entries"; if (!entries.length) { const empty = element("div", "empty-results"); empty.append(element("span", "empty-icon", "—"), element("p", "No immediate entries."), element("small", "This directory is empty or all of its children are excluded.")); dom.results.append(empty); return; } entries.forEach((entry) => { const button = element("button", "result browse-entry"); button.type = "button"; button.dataset.key = entry.key; const meta = element("div", "result-meta"); meta.append(element("span", "host-tag", entry.host), element("span", "", entry.kind), element("span", "", entry.size == null ? "" : `${entry.size} bytes`)); button.append(element("div", "result-path", entry.name), element("div", "result-snippet", entry.path), meta); button.addEventListener("click", () => selectBrowseEntry(entry, button)); dom.results.append(button); }); }
  async function browseDirectory(target) { if (!target?.host || !target?.path) return; state.browseTarget = target; setSearchState("running", `Listing immediate entries in ${target.path}…`); dom.count.textContent = "Loading entries…"; try { const payload = await request(api.browse, { method: "POST", body: JSON.stringify({ host: target.host, path: target.path }) }); if (state.browseTarget !== target) return; renderBrowseEntries(normalizeEntries(payload, target.host)); setSearchState("complete", `Listed immediate entries in ${target.path}.`); } catch (error) { if (state.browseTarget !== target) return; clear(dom.results).append(element("div", "empty-results", `Browse unavailable: ${errorMessage(error)}`)); dom.count.textContent = "Browse unavailable"; setSearchState("error", `Browse failed: ${errorMessage(error)}`); } }
  function selectBrowseEntry(entry, button) { state.selected = entry; document.querySelectorAll(".browse-entry.selected").forEach((item) => item.classList.remove("selected")); button.classList.add("selected"); browseEntryDetails(entry); if (entry.kind === "directory") browseDirectory(entry); }
  function normalizeResults(payload) { const source = dataOf(payload); const raw = pick(source, ["results", "matches", "hits"], []); return (Array.isArray(raw) ? raw : []).map((item, index) => ({ previewId: text(pick(item, ["preview_id"], "")), host: text(pick(item, ["host_id", "host"], "local")), path: text(pick(item, ["path", "file"], "")), line: Number(pick(item, ["line_number", "line", "start_line"], 1)) || 1, snippet: text(pick(item, ["snippet", "text", "line_text", "match"], "")), key: `${pick(item, ["preview_id", "id"], "")}:${index}` })).filter((item) => item.path || item.previewId); }
  function statusDetails(payload) { const source = dataOf(payload); const hostStatus = pick(source, ["host_status", "hosts"], []); const failures = (Array.isArray(hostStatus) ? hostStatus : []).filter((item) => item && item.ok === false).map((item) => ({ host: text(pick(item, ["host_id", "host", "id"], "unknown host")), error: text(pick(item, ["error", "message"], "No error detail was returned.")) })); return { partial: Boolean(pick(source, ["partial"], false)), truncated: Boolean(pick(source, ["truncated"], false)), failures }; }
  function renderHostFailures(failures) { clear(dom.failures); if (!failures.length) { dom.failures.hidden = true; return; } dom.failures.append(element("p", "host-failures-heading", "Mesh host errors")); failures.forEach((failure) => { const item = element("div", "host-failure"); item.append(element("strong", "", `Host ${failure.host} reported an error`), element("code", "", failure.error)); dom.failures.append(item); }); dom.failures.hidden = false; }
  function renderResults(results) { clear(dom.results); if (!results.length) { const empty = element("div", "empty-results"); empty.append(element("span", "empty-icon", "—"), element("p", "No matching files."), element("small", "Try a different query or broader permitted scope.")); dom.results.append(empty); return; } results.forEach((result) => { const button = element("button", "result"); button.type = "button"; button.dataset.key = result.key; const meta = element("div", "result-meta"); meta.append(element("span", "host-tag", result.host), element("span", "", `line ${result.line}`)); button.append(element("div", "result-path", result.path || "Previewable result"), element("div", "result-snippet", result.snippet || "Open bounded preview"), meta); button.addEventListener("click", () => selectResult(result, button)); dom.results.append(button); }); }
  function renderSearch(payload) { const source = dataOf(payload); state.mode = "search"; state.results = normalizeResults(payload); renderResults(state.results); dom.count.textContent = formatCount(state.results.length); const details = statusDetails(payload); renderHostFailures(details.failures); if (details.partial) setSearchState("partial", `Partial result: ${details.failures.length || "one or more"} host responses were unavailable.`); else if (details.truncated) setSearchState("truncated", "Results are truncated to the allowed limit. Narrow the query or scope."); else if (pick(source, ["state", "status"], "") === "running") setSearchState("running", "Search is still running; wait for the local API to finish."); else setSearchState("complete", state.results.length ? "Search complete." : "Search complete with no matches."); if (details.partial && details.truncated) setSearchState("partial", "Partial result and truncated result set. Narrow the query, then retry."); }
  async function pollSearch(payload) { let current = payload; renderSearch(current); while (pick(dataOf(current), ["state"], "") === "running") { const source = dataOf(current); const jobId = pick(source, ["job_id"]); if (!jobId) throw new Error("The local API did not return a search job ID."); const delay = Math.max(25, Math.min(500, Number(pick(source, ["next_poll_after_ms"], 100)) || 100)); await new Promise((resolve) => setTimeout(resolve, delay)); current = await request(api.searchStatus, { method: "POST", body: JSON.stringify({ job_id: jobId }) }); renderSearch(current); } return current; }
  async function performSearch(event) { event.preventDefault(); const query = dom.query.value.trim(); if (!query) { dom.query.focus(); setSearchState("error", "Enter text or a pattern before searching."); return; } dom.button.disabled = true; dom.button.firstElementChild.textContent = "Searching"; setSearchState("running", "Searching available hosts…"); dom.count.textContent = "Searching…"; state.selected = null; try { const body = { query, hosts: state.selectedHost ? [state.selectedHost] : undefined, roots: state.selectedRoot ? [state.selectedRoot] : undefined }; Object.keys(body).forEach((key) => body[key] === undefined && delete body[key]); await pollSearch(await request(api.search, { method: "POST", body: JSON.stringify(body) })); } catch (error) { dom.count.textContent = "Search unavailable"; setSearchState("error", `Search failed: ${errorMessage(error)}`); clear(dom.results).append(element("div", "empty-results", "The local API did not return results.")); } finally { dom.button.disabled = false; dom.button.firstElementChild.textContent = "Search"; } }
  function previewText(payload) { const source = dataOf(payload); if (typeof source.text === "string") return source.text; if (typeof source.content === "string") return source.content; if (Array.isArray(source.chunks)) return source.chunks.map((chunk) => typeof chunk === "string" ? chunk : pick(chunk, ["text", "content"], "")).join("\n"); return "No preview text was returned."; }
  async function selectResult(result, button) { state.selected = result; document.querySelectorAll(".result.selected").forEach((item) => item.classList.remove("selected")); button.classList.add("selected"); if (!result.previewId) { clear(dom.preview).className = "preview-error"; dom.preview.textContent = "Preview is unavailable because this result has no server-issued preview ID."; return; } clear(dom.preview).className = "preview-loading"; dom.preview.textContent = "Loading bounded preview…"; try { const payload = await request(api.preview, { method: "POST", body: JSON.stringify({ preview_id: result.previewId }) }); if (state.selected !== result) return; const source = dataOf(payload); const content = clear(dom.preview); content.className = "preview-content"; const title = element("div", "preview-title"); title.append(element("code", "", text(pick(source, ["path"], result.path || "Selected result"))), element("span", "", `line ${pick(source, ["start_line", "line"], result.line)}`)); content.append(title, element("pre", "", previewText(payload))); } catch (error) { clear(dom.preview).className = "preview-error"; dom.preview.textContent = `Preview unavailable: ${errorMessage(error)}`; } }
  function renderBackup(payload) { const source = dataOf(payload); const rawState = text(pick(source, ["state", "status"], "unconfigured")).toLowerCase(); const valid = ["available", "stale", "unavailable", "unconfigured"].includes(rawState) ? rawState : "unconfigured"; const descriptions = { available: "A backup catalog is available.", stale: "A backup catalog is available, but its metadata is stale.", unavailable: "The backup catalog is currently unavailable.", unconfigured: "No backup catalog is configured for this Console." }; dom.backupBadge.className = `backup-state ${valid}`; dom.backupBadge.textContent = valid; const body = clear(dom.backup); body.append(element("p", "", pick(source, ["message", "detail"], descriptions[valid]))); const count = pick(source, ["snapshot_count", "count", "entries"]); const updated = pick(source, ["updated_at", "generated_at", "checked_at"]); if (count !== undefined || updated) { const meta = element("div", "backup-meta"); if (count !== undefined) meta.append(element("span", "", `${count} catalog entries`)); if (updated) meta.append(element("span", "", `Updated ${updated}`)); body.append(meta); } body.append(element("small", "", "Backup status is separate from live search. No restore or backup-content search is performed here.")); }
  async function loadBackup() { try { renderBackup(await request(api.backup)); } catch (error) { renderBackup({ state: "unavailable", message: `Backup catalog check failed: ${errorMessage(error)}` }); } }
  dom.form.addEventListener("submit", performSearch); dom.locations.addEventListener("click", selectLocation); dom.refresh.addEventListener("click", () => { loadCatalog(); loadBackup(); }); loadCatalog(); loadBackup();
})();
